# Generated by Django 2.1.1 on 2018-10-18 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(choices=[('LU', 'luigi'), ('MA', 'mario'), ('DK', 'donkey_kong'), ('LI', 'link'), ('SA', 'samus'), ('CF', 'captain_falcon'), ('NE', 'ness'), ('YO', 'yoshi'), ('KI', 'kirby'), ('FO', 'fox'), ('PI', 'pikachu'), ('PU', 'purin')], max_length=2)),
                ('rate', models.IntegerField(default=1500)),
                ('playable', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='handle_name')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winloss', models.BooleanField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='ratesmash.Player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='ratesmash.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('w', 'wait'), ('d', 'during'), ('f', 'finish'), ('p', 'processing')], default='w', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratesmash.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratesmash.Player')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ratesmash.Room')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratesmash.Room'),
        ),
    ]
