# Generated by Django 2.1.1 on 2018-10-20 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratesmash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='comment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='ratesmash.Player'),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='ratesmash.Player'),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
