# Generated by Django 2.1.1 on 2018-10-21 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ratesmash', '0002_auto_20181020_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='server',
            field=models.CharField(choices=[('tetsu', 'tetsu_server'), ('kaillera', 'kaillera_server'), ('exo', 'exo_server')], default='tetsu', max_length=10),
            preserve_default=False,
        ),
    ]
