# Generated by Django 2.1.1 on 2018-10-21 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ratesmash', '0003_auto_20181021_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
