# Generated by Django 2.1.1 on 2018-10-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratesmash', '0004_auto_20181021_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cf',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
