# Generated by Django 2.1.2 on 2018-11-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratesmash', '0005_room_cf'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mask',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
