# Generated by Django 2.1.2 on 2018-11-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratesmash', '0006_room_mask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='mask',
            new_name='mode',
        ),
    ]
