# Generated by Django 2.1.2 on 2018-11-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratesmash', '0007_auto_20181115_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='server',
            field=models.CharField(choices=[('tetsu', 'tetsu_server'), ('kaillera', 'kaillera_server'), ('exo', 'exo_server'), ('heijokyo', 'heijokyo')], max_length=10),
        ),
    ]
