# Generated by Django 2.1.2 on 2018-11-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratesmash', '0009_auto_20181117_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rate_o',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='rate_p',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
